app:App
	java App
    
App:Controller Model View
	javac App.java
    
Controller: Controller.java
	javac Controller.java

Model:Model.java
	javac Model.java
    
View:View.java
	javac View.java
    
clean:
	rm -f *.class